version: '3.7'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
      - solr_data:/usr/src/app/solr_data
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - solr
  db:
    image: postgres:12.0-alpine
    volumes:
      - ../postgres_data_dev:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=comohay
      - POSTGRES_PASSWORD=comohay
      - POSTGRES_DB=comohay_dev
    ports:
      - 5433:5432
  redis:
    image: redis:5.0
    expose:
      - "6379"
  celery_worker:
    build: ./
    command: celery worker --app=comohay --loglevel=info -Q celery,telegram_messages
    volumes:
      - ./:/usr/src/app/
      - solr_data:/usr/src/app/solr_data
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - db
      - redis
  celery_beat:
    build: ./
    command: celery beat --app=comohay --loglevel=info --pidfile=
    volumes:
      - ./:/usr/src/app/
      - solr_data:/usr/src/app/solr_data
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - db
      - redis
  solr:
    image: solr:6.6
    ports:
      - 8983:8983
    volumes:
      - solr_data:/opt/solr/server/solr/mycores/
    command:
      - solr-precreate
      - ads
      - /opt/solr/server/solr/configsets/basic_configs
volumes:
  postgres_data:
  solr_data: