version: '3.7'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
      - solr_data:/usr/src/app/solr_data
      - telethon_sessions:/usr/src/app/telethon_sessions
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - solr
  db:
    image: postgres:12.0-alpine
    volumes:
      - ../postgres_data_dev:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=comohay
      - POSTGRES_PASSWORD=comohay
      - POSTGRES_DB=comohay_dev
    ports:
      - 5433:5432
  redis:
    image: redis:6.2.6
    expose:
      - "6379"
  celery_worker_1:
    build: ./
    command: celery --app comohay worker --loglevel=info -Q celery,ads_crawl,updater -n worker1@%h
    volumes:
      - ./:/usr/src/app/
      - solr_data:/usr/src/app/solr_data
      - telethon_sessions:/usr/src/app/telethon_sessions
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - db
      - redis
  celery_worker_2:
    build: ./
    command: celery --app comohay worker --loglevel=info -Q telegram -n worker2@%h
    volumes:
      - ./:/usr/src/app/
      - solr_data:/usr/src/app/solr_data
      - telethon_sessions:/usr/src/app/telethon_sessions
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - db
      - redis
  celery_beat:
    build: ./
    command: celery --app comohay beat --loglevel=info --pidfile=
    volumes:
      - ./:/usr/src/app/
      - solr_data:/usr/src/app/solr_data
      - telethon_sessions:/usr/src/app/telethon_sessions
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - db
      - redis
  solr:
    platform: linux/amd64
    image: solr:6.6
    ports:
      - 8983:8983
    volumes:
      - solr_data:/opt/solr/server/solr/mycores/
      - ./solr_conf/ads_core_stopwords_es.txt:/home/ads_stopwords_es.txt
    command: 'bash -e -c "precreate-core ads /opt/solr/server/solr/configsets/basic_configs; cp /home/ads_stopwords_es.txt /opt/solr/server/solr/mycores/ads/conf/lang/stopwords_es.txt; solr-foreground;"'
volumes:
  postgres_data:
  solr_data:
  telethon_sessions: