# Generated by Django 3.0.7 on 2021-09-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel('ExchangeRate'),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_currency_iso', models.CharField(max_length=3)),
                ('target_currency_iso', models.CharField(max_length=3)),
                ('type', models.CharField(choices=[('buy', 'Buy price'), ('sell', 'Sell price'), ('mid', 'Mid price')],
                                          max_length=10)),
                ('wavg', models.FloatField()),
                ('max', models.FloatField()),
                ('min', models.FloatField()),
                ('mad', models.FloatField()),
                ('median', models.FloatField()),
                ('days_span', models.IntegerField()),
                ('max_mzscore', models.FloatField()),
                ('ads_qty', models.IntegerField()),
                ('datetime', models.DateTimeField()),
            ],
        )
    ]
