# Generated by Django 3.0.5 on 2020-04-22 21:55

from django.db import migrations

from ads.models.municipality import Municipality
from ads.models.province import Province

province_codes = {
    '23': 'La Habana',
    '25': 'Matanzas',
    '27': 'Cienfuegos',
    '28': 'Sancti Spíritus',
    '31': 'Las Tunas',
    '32': 'Holguín',
    '33': 'Granma',
    '34': 'Santiago de Cuba',
    '40': 'Isla de la Juventud',
    '30': 'Camagüey',
    '29': 'Ciego de Ávila',
    '26': 'Villa Clara',
    '35': 'Guantánamo',
    '21': 'Pinar del Río',
    '22': 'Artemisa',
    '24': 'Mayabeque'
}

def add_provinces(apps, schema_editor):
    for code in province_codes:
        p = Province(code=code, name=province_codes[code])
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_provinces),
    ]
