# Generated by Django 3.0.5 on 2020-04-26 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_ad_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='url',
            new_name='external_url',
        ),
    ]
