# Generated by Django 3.0.6 on 2020-06-01 16:07

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_auto_20200601_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='updated_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='ad_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
    ]
