# Generated by Django 3.0.5 on 2020-05-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_include_categories_20200501_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='external_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='external_source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
