# Generated by Django 3.0.7 on 2020-06-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_auto_20200601_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='currency',
            field=models.CharField(blank=True, choices=[('CUC', 'CUC'), ('CUP', 'CUP'), ('USD', 'USD')], default='CUC', max_length=3, null=True, verbose_name='Currency'),
        ),
    ]
