# Generated by Django 3.0.7 on 2020-06-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_ad_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='currency',
        ),
        migrations.AddField(
            model_name='ad',
            name='user_currency',
            field=models.CharField(blank=True, choices=[('CUC', 'CUC'), ('CUP', 'CUP')], default='CUC', max_length=3, null=True, verbose_name='Currency'),
        ),
    ]
