# Generated by Django 3.0.7 on 2020-06-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_auto_20200607_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='user_currency',
            field=models.CharField(choices=[('CUC', 'CUC'), ('CUP', 'CUP')], default='CUC', max_length=3, null=True, verbose_name='Currency'),
        ),
    ]
