# Generated by Django 3.0.7 on 2020-06-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_auto_20200608_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=64, null=True, verbose_name='Price'),
        ),
    ]
