# Generated by Django 3.0.7 on 2020-07-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0013_enable_postgress_trigram_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact email'),
        ),
        migrations.AddField(
            model_name='ad',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Contact phone'),
        ),
    ]
