# Generated by Django 3.0.7 on 2020-07-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0014_add_ad_contacts_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersearch',
            name='autosuggestion',
            field=models.BooleanField(default=False, verbose_name='Autosuggestion'),
        ),
    ]
