# Generated by Django 3.0.7 on 2020-07-16 02:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0015_usersearch_autosuggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersearch',
            name='daystamp',
        ),
        migrations.AddField(
            model_name='usersearch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
    ]
