# Generated by Django 3.0.7 on 2021-01-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0019_auto_20200928_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='user_currency',
            field=models.CharField(choices=[('CUC', 'CUC'), ('CUP', 'CUP'), ('USD', 'USD')], default='CUP', max_length=3, null=True, verbose_name='Currency'),
        ),
    ]
