# Generated by Django 3.0.7 on 2021-01-06 15:00

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0020_add_usd_currency_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', verbose_name='Slug'),
        ),
    ]
