# Generated by Django 3.0.7 on 2021-08-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0022_add_anonymous_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='user_currency',
            new_name='currency_iso',
        ),
        migrations.AlterField(
            model_name='ad',
            name='currency_iso',
            field=models.CharField(choices=[('CUP', 'CUP'), ('MLC', 'MLC'), ('USD', 'USD'), ('EUR', 'EUR'), ('CAD', 'CAD'), ('MXN', 'MXN'), ('CUC', 'CUC')], default='CUP', max_length=3, null=True, verbose_name='Currency'),
        )
    ]
