# Generated by Django 3.0.7 on 2021-08-28 01:03

from django.db import migrations
from django.db.models import F


def convert_prices_to_cuc_usd(apps, schema_editor):
    Ad = apps.get_model('ads', 'Ad')
    Ad.objects.filter(currency_iso__in=('CUC', 'USD')).update(price=F('price') / 25)


def convert_prices_to_cup(apps, schema_editor):
    Ad = apps.get_model('ads', 'Ad')
    Ad.objects.filter(currency_iso__in=('CUC', 'USD')).update(price=F('price') * 25)


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0023_auto_20210828_0018'),
    ]

    operations = [
        migrations.RunPython(code=convert_prices_to_cuc_usd, reverse_code=convert_prices_to_cup)
    ]
