# Generated by Django 3.0.7 on 2021-08-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0024_auto_20210828_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
