# Generated by Django 3.0.7 on 2021-08-29 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0026_ad_contact_tg'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase')], max_length=9)),
                ('source_currency_iso', models.CharField(choices=[('CUP', 'CUP'), ('MLC', 'MLC'), ('USD', 'USD'), ('EUR', 'EUR'), ('CAD', 'CAD'), ('MXN', 'MXN'), ('CUC', 'CUC')], max_length=3)),
                ('target_currency_iso', models.CharField(choices=[('CUP', 'CUP'), ('MLC', 'MLC'), ('USD', 'USD'), ('EUR', 'EUR'), ('CAD', 'CAD'), ('MXN', 'MXN'), ('CUC', 'CUC')], max_length=3)),
                ('price', models.FloatField()),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.Ad')),
            ],
        ),
    ]
