# Generated by Django 3.0.7 on 2021-09-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0027_telegramgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramgroup',
            name='link',
            field=models.URLField(unique=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='telegramgroup',
            name='username',
            field=models.CharField(max_length=32, unique=True, verbose_name='Username'),
        ),
    ]
