# Generated by Django 3.0.7 on 2021-08-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0027_currencyad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyad',
            name='source_currency_iso',
            field=models.CharField(choices=[('CUP', 'CUP'), ('MLC', 'MLC'), ('USD', 'USD'), ('EUR', 'EUR'), ('CAD', 'CAD'), ('MXN', 'MXN')], max_length=3),
        ),
        migrations.AlterField(
            model_name='currencyad',
            name='target_currency_iso',
            field=models.CharField(choices=[('CUP', 'CUP'), ('MLC', 'MLC'), ('USD', 'USD'), ('EUR', 'EUR'), ('CAD', 'CAD'), ('MXN', 'MXN')], max_length=3),
        ),
    ]
