# Generated by Django 3.0.7 on 2021-10-23 20:47

from django.db import migrations
from django.db.migrations import AddIndex
from django.db.models import Index


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0029_add_deleted_at_field_to_ad_table'),
    ]

    operations = [
        AddIndex('Ad', Index(fields=['external_url'], name='ads_ad_external_url__index')),
        AddIndex('Ad', Index(fields=['external_source', 'external_id'], name='ads_ad_external_source_external_id__index'))
    ]
