# Generated by Django 3.0.7 on 2021-09-06 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0026_ad_contact_tg'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_currency_iso', models.CharField(max_length=3)),
                ('target_currency_iso', models.CharField(max_length=3)),
                ('type', models.CharField(choices=[('buy', 'Buy price'), ('sell', 'Sell price'), ('mid', 'Mid price')], max_length=10)),
                ('wavg', models.FloatField()),
                ('max', models.FloatField()),
                ('min', models.FloatField()),
                ('mad', models.FloatField()),
                ('median', models.FloatField()),
                ('days_span', models.IntegerField()),
                ('max_mzscore', models.FloatField()),
                ('ads_qty', models.IntegerField()),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase')], max_length=9)),
                ('source_currency_iso', models.CharField(choices=[('CUP', 'CUP'), ('MLC', 'MLC'), ('USD', 'USD'), ('EUR', 'EUR'), ('CAD', 'CAD'), ('MXN', 'MXN')], max_length=3)),
                ('target_currency_iso', models.CharField(choices=[('CUP', 'CUP'), ('MLC', 'MLC'), ('USD', 'USD'), ('EUR', 'EUR'), ('CAD', 'CAD'), ('MXN', 'MXN')], max_length=3)),
                ('price', models.FloatField()),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.Ad')),
            ],
        ),
    ]
