# Generated by Django 3.0.7 on 2021-09-15 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangerate',
            old_name='max_mzscore',
            new_name='deviation_threshold',
        ),
    ]
